### ISSUE TITLE
What is os.environ in the code?

### ISSUE THREAD

**Issue by ppwater01** [SO-Close-Vote-Reviewers-2-BOT/so-close-vote-reviewers-2-bot#3]
I see a `os.environ` in the code. what does it do, and how do I set it? 

Mentioning the author @Victor-VosMottor

**Comment by Victor-VosMottor** [comment]
[This is a good article on it](https://www.geeksforgeeks.org/python-os-environ-object/). In brief it's called environment variable, you can set [this way](https://askubuntu.com/questions/58814/how-do-i-add-environment-variables). It's added for security reasons as it's not a good idea to store login and password in the source code.

**Comment by ppwater01** [comment]
Ah, thanks.

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 Actually @Victor-VosMottor told me about this before. When he joined the organization he made some changes and I noticed that in teh codez he added `os.environ` and some other things similar to that, I asked him about it, and he told me about it but I wasn't here on GH the entire time you guys were commenting so I wasn't able to comment and answer your question.
