### ISSUE TITLE
What shall be the first command?

### ISSUE THREAD

**Issue by ppwater01** [SO-Close-Vote-Reviewers-2-BOT/so-close-vote-reviewers-2-bot#9]
What should it be?

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 Hmm, I don't know, I think you and @Victor-VosMottor might know more about it as both of you are familiar with SmokeDetector (you guys are Charcoalers with privs but I don't, I can only flag things that SmokeDetector reports). @Ann-Zen Got any suggestions? Thanks! P.S. I *do* know one thing. Our first command *definitely cannot* be a fun command like SmokeDetector's `blame`, `coffee`, `lick`, and `tea` commands. That is pretty obvious to me. :P

**Comment by ppwater01** [comment]
@Tech-Expert-Wizard https://github.com/Charcoal-SE/SmokeDetector/wiki/Commands#wiki-wrapper

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 Thanks!

**Comment by Tech-Expert-Wizard** [comment]
@ppwater01 @Victor-VosMottor @Ann-Zen After quickly scanning through the document linked above, I believe that maybe we should start simple with an `alive` command. I know `alive` isn't really important, but it's really easy to implement and can count as a good start.

**Comment by ppwater01** [comment]
@Tech-Expert-Wizard Good Idea. I'll raise a PR
